SELECT DISTINCT P.NAME
FROM OWNERR O
JOIN AIRPLANE A ON O.OID = A.OWN
JOIN AIRPLANE_TYPE T ON A.TYPEE = T.MODELNO
JOIN SERVICERECORDS S ON A.REGNO = S.REGNUMBER
JOIN EMP E ON S.EID = E.EID
JOIN PERSON P ON O.PERSON = P.SSN
WHERE E.EID NOT IN (
  SELECT EID
  FROM EMP_CANWORKON
  WHERE Can_Work = T.MODELNO
);