SELECT 
   CASE
      WHEN OWNERR.OWNERTYPE = 'Individual' THEN PERSON.NAME
      WHEN OWNERR.OWNERTYPE = 'Corporate' THEN COORPORATIONS.CNAME
   END AS OWNER_NAME,
   CASE
      WHEN OWNERR.OWNERTYPE = 'Individual' THEN PERSON.ADDR
      WHEN OWNERR.OWNERTYPE = 'Corporate' THEN COORPORATIONS.ADDRESS
   END AS ADDRESS
FROM OWNERR
LEFT JOIN PERSON ON OWNERR.PERSON = PERSON.SSN
LEFT JOIN COORPORATIONS ON OWNERR.CID = COORPORATIONS.CNAME
WHERE PERSON.NAME IS NOT NULL or COORPORATIONS.CNAME IS NOT NULL;