SELECT DISTINCT EMP.EID, SUM(SERVICERECORDS.HOURSWORKED) AS TOTAL_HOURS_WORKED
FROM EMP
JOIN SERVICERECORDS ON EMP.EID = SERVICERECORDS.EID
JOIN AIRPLANE ON AIRPLANE.REGNO = SERVICERECORDS.REGNUMBER
JOIN OWNERR ON OWNERR.OID = AIRPLANE.OWN
JOIN COORPORATIONS ON COORPORATIONS.CNAME = OWNERR.CID
WHERE COORPORATIONS.CNAME = 'Acme Corp'
GROUP BY EMP.EID
ORDER BY TOTAL_HOURS_WORKED DESC;