SELECT A.ANAME, A.REGNO
FROM AIRPLANE A
WHERE A.OWN NOT IN (SELECT OID FROM OWNERR WHERE CID IS NOT NULL)
AND A.REGNO NOT IN (SELECT SR.REGNUMBER FROM SERVICERECORDS SR JOIN EMP E ON SR.EID=E.EID WHERE E.SHIFTTIME='Morning')