SELECT 
    CASE 
        WHEN OWNERR.PERSON IS NOT NULL THEN PERSON.NAME
        ELSE COORPORATIONS.CNAME
    END AS OWNER_NAME,
    COUNT(AIRPLANE.OWN) AS TOTAL_PLANES_OWNED
FROM 
    AIRPLANE
    INNER JOIN OWNERR ON AIRPLANE.OWN = OWNERR.OID
    LEFT JOIN PERSON ON OWNERR.PERSON = PERSON.SSN
    LEFT JOIN COORPORATIONS ON OWNERR.CID = COORPORATIONS.CNAME
GROUP BY 
    CASE 
        WHEN OWNERR.PERSON IS NOT NULL THEN PERSON.NAME
        ELSE COORPORATIONS.CNAME
    END