SELECT AIRPLANE.ANAME, AIRPLANE.REGNO
FROM AIRPLANE
INNER JOIN SERVICERECORDS
ON AIRPLANE.REGNO = SERVICERECORDS.REGNUMBER
WHERE SERVICERECORDS.SERVICEDATE BETWEEN DATEADD(week, -1, GETDATE()) AND GETDATE();