SELECT DISTINCT OWNERR.CID, OWNERR.PERSON, PERSON.PHONE
FROM AIRPLANE
INNER JOIN OWNERR ON AIRPLANE.OWN = OWNERR.OID
INNER JOIN PERSON ON OWNERR.PERSON = PERSON.SSN
WHERE AIRPLANE.PDATE >= DATEADD(MONTH, -1, GETDATE())